import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import { ToastProvider } from '@/context/toastContext';
import { ToastContainer } from 'react-toastify';
import { Suspense } from 'react';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  display: 'swap',
});
export const metadata = {
  title: 'Highway Delite',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo.svg',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.className} antialiased`}>
      <body>
        <ToastProvider>
          <Suspense fallback={
            <nav className="text-amber-10 hd-bg-color flex sm:flex-row justify-between items-center gap-3 sm:gap-0 min-h-20 px-4 sm:px-8 md:px-12 lg:px-20 py-3 sm:py-2 shadow-md">
              <div className="left w-sm sm:w-auto flex justify-center sm:justify-start">
                <img src="/logo.svg" alt="Highway Delite Logo" className="h-5 sm:h-12" />
              </div>
            </nav>
          }>
            <Navbar />
          </Suspense>
          {children}
          <ToastContainer />
        </ToastProvider>
      </body>
    </html>
  );
}
